import { useState } from 'react';

interface NodeInfo {
  id: string;
  type: string;
  data: any;
}

interface ConsolePopupProps {
  isOpen: boolean;
  onClose: () => void;
  logs: string;
  nodes: NodeInfo[];
  nodeStatuses: Record<string, 'running' | 'complete' | 'error' | null>;
  errors: Record<string, string>;
  nodeOutputs: Record<string, any[]>; // e.g. tables or images generated by node
  onLocateNode?: (nodeId: string) => void;
}

export default function ConsolePopup({
  isOpen,
  onClose,
  logs,
  nodes,
  nodeStatuses,
  errors,
  nodeOutputs,
  onLocateNode,
}: ConsolePopupProps) {
  const [selectedFilter, setSelectedFilter] = useState<string>('all');
  const [activeTab, setActiveTab] = useState<'logs' | 'outputs'>('logs');

  if (!isOpen) return null;

  // Group logs by Node
  const logLines = logs.split('\n');
  const groupedLogs: Record<string, string[]> = { global: [] };
  let currentNodeId = 'global';

  logLines.forEach((line) => {
    if (line.includes('##NODE_START:')) {
      const match = line.match(/##NODE_START:([^\s]+)/);
      if (match) {
        currentNodeId = match[1].trim();
        if (!groupedLogs[currentNodeId]) {
          groupedLogs[currentNodeId] = [];
        }
      }
    } else if (line.includes('##NODE_COMPLETE:') || line.includes('##NODE_ERROR:')) {
      // Revert to global after a node completes or errors out
      currentNodeId = 'global';
    } else if (line.includes('##NODE_ERROR_MSG:')) {
      // Do not append raw markers to console text
    } else if (line.includes('##PLOT:')) {
      // Do not append plot markers to raw console text
    } else if (line.includes('##NODE_OUTPUT:')) {
      // Do not append output JSON markers to raw console text
    } else {
      if (!groupedLogs[currentNodeId]) {
        groupedLogs[currentNodeId] = [];
      }
      // Only append if it's not a marker
      if (!line.startsWith('##')) {
        groupedLogs[currentNodeId].push(line);
      }
    }
  });

  const getCategoryColor = (type: string) => {
    switch (type) {
      case 'data_input': return 'bg-blue-500/20 text-blue-400 border-blue-500/30';
      case 'preprocessing': return 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30';
      case 'model_training': return 'bg-orange-500/20 text-orange-400 border-orange-500/30';
      case 'evaluation': return 'bg-teal-500/20 text-teal-400 border-teal-500/30';
      default: return 'bg-gray-500/20 text-gray-400 border-gray-500/30';
    }
  };

  const getNodeTitle = (node: NodeInfo) => {
    switch (node.type) {
      case 'data_input': return '📊 Data Input';
      case 'model_training': return '⚙️ Model Training';
      case 'evaluation': return '📈 Evaluation';
      default: return `Node: ${node.id}`;
    }
  };

  const filteredNodeIds = selectedFilter === 'all' 
    ? ['global', ...nodes.map(n => n.id)] 
    : [selectedFilter];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-6 bg-black/80 backdrop-blur-md">
      <div className="flex flex-col w-full h-full max-w-6xl glass-panel border border-border rounded-2xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-bg-panel/50">
          <div className="flex items-center gap-3">
            <span className="text-xl">🖥️</span>
            <div>
              <h2 className="font-bold text-text-primary text-base">Pipeline Output Terminal</h2>
              <p className="text-xs text-text-secondary">Inspect live execution trace blocks and compiled artifacts</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="px-3 py-1.5 rounded-lg border border-border bg-bg-card hover:bg-bg-hover text-text-secondary hover:text-text-primary text-xs transition"
          >
            ✕ Close Terminal
          </button>
        </div>

        {/* Filters and Tabs */}
        <div className="flex flex-wrap items-center justify-between px-6 py-3 border-b border-border bg-bg-panel/20 gap-3">
          {/* Node Selector Filter */}
          <div className="flex items-center gap-2">
            <span className="text-xs text-text-muted">Filter by Node:</span>
            <select
              value={selectedFilter}
              onChange={(e) => setSelectedFilter(e.target.value)}
              className="bg-bg-card border border-border text-text-primary text-xs rounded-lg px-2.5 py-1.5 focus:outline-none focus:border-blue-500"
            >
              <option value="all">🔍 All Execution Blocks</option>
              <option value="global">🌐 System Logs</option>
              {nodes.map(node => (
                <option key={node.id} value={node.id}>
                  {node.id.split('_')[0].toUpperCase()} - {node.id}
                </option>
              ))}
            </select>
          </div>

          {/* Logs vs Outputs Tabs Toggle */}
          <div className="flex gap-1 bg-slate-200/60 dark:bg-bg-card p-1 border border-border rounded-lg shadow-inner">
            <button
              onClick={() => setActiveTab('logs')}
              className={`px-4 py-1.5 text-xs font-semibold rounded-md transition ${
                activeTab === 'logs' 
                  ? 'bg-blue-600 text-white shadow-md font-bold' 
                  : 'text-text-secondary hover:text-text-primary hover:bg-slate-300/40 dark:hover:bg-bg-hover'
              }`}
            >
              Console Logs
            </button>
            <button
              onClick={() => setActiveTab('outputs')}
              className={`px-4 py-1.5 text-xs font-semibold rounded-md transition ${
                activeTab === 'outputs' 
                  ? 'bg-blue-600 text-white shadow-md font-bold' 
                  : 'text-text-secondary hover:text-text-primary hover:bg-slate-300/40 dark:hover:bg-bg-hover'
              }`}
            >
              Proper Outputs
            </button>
          </div>
        </div>

        {/* Content Pane */}
        <div className="flex-1 overflow-y-auto p-6 custom-scrollbar text-left" style={{ backgroundColor: 'var(--bg-console)' }}>
          {activeTab === 'logs' ? (
            // LOGS VIEW
            <div className="space-y-6">
              {filteredNodeIds.map((nid) => {
                const logsForNode = groupedLogs[nid] || [];
                const node = nodes.find(n => n.id === nid);
                const status = nodeStatuses[nid];
                const error = errors[nid];

                if (nid !== 'global' && !node) return null;
                if (nid === 'global' && logsForNode.length === 0) return null;

                return (
                  <div key={nid} className="border border-border/80 rounded-xl overflow-hidden bg-bg-panel/40">
                    {/* Block Title Bar */}
                    <div className="flex flex-wrap items-center justify-between px-4 py-2 bg-bg-panel/80 border-b border-border gap-2">
                      <div className="flex items-center gap-2">
                        {node ? (
                          <span className={`text-[10px] px-2 py-0.5 rounded-md font-bold uppercase border ${getCategoryColor(node.type)}`}>
                            {getNodeTitle(node)}
                          </span>
                        ) : (
                          <span className="text-[10px] px-2 py-0.5 rounded-md font-bold uppercase bg-gray-500/20 text-gray-400 border border-border">
                            🌐 System / Global Log
                          </span>
                        )}
                        <span className="text-xs text-text-muted font-mono">{nid}</span>
                      </div>
                      <div className="flex items-center gap-3">
                        {status && (
                          <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase ${
                            status === 'running' ? 'bg-orange-500/20 text-orange-400 border border-orange-500/30' :
                            status === 'complete' ? 'bg-green-500/20 text-green-400 border border-green-500/30' :
                            'bg-red-500/20 text-red-400 border border-red-500/30'
                          }`}>
                            {status}
                          </span>
                        )}
                        {node && onLocateNode && (
                          <button
                            onClick={() => onLocateNode(node.id)}
                            className="text-[10px] text-blue-400 hover:text-blue-300 font-semibold underline transition cursor-pointer"
                          >
                            Locate Node
                          </button>
                        )}
                      </div>
                    </div>

                    {/* Block Outputs */}
                    <div className="p-4 font-mono text-xs whitespace-pre-wrap leading-relaxed" style={{ color: 'var(--text-console)' }}>
                      {logsForNode.length > 0 ? (
                        logsForNode.join('\n')
                      ) : (
                        <span className="text-text-muted italic">No stdout logs emitted from this execution block.</span>
                      )}

                      {/* Display traceback error block */}
                      {error && (
                        <div className="mt-4 p-4 border border-red-500/30 rounded-lg bg-red-500/10 text-red-400 font-sans">
                          <div className="flex items-center gap-2 mb-2 font-bold">
                            <span>❌ Execution Error Traceback:</span>
                          </div>
                          <pre className="font-mono text-xs whitespace-pre-wrap text-red-300 bg-red-950/20 p-2 rounded border border-red-500/10 max-h-40 overflow-y-auto">
                            {error}
                          </pre>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            // PROPER OUTPUTS VIEW
            <div className="space-y-6">
              {filteredNodeIds.map((nid) => {
                const node = nodes.find(n => n.id === nid);
                const outputs = nodeOutputs[nid] || [];

                if (nid === 'global') return null;
                if (!node) return null;

                return (
                  <div key={nid} className="border border-border/80 rounded-xl overflow-hidden bg-bg-panel/40">
                    <div className="flex items-center justify-between px-4 py-2 bg-bg-panel/80 border-b border-border">
                      <span className={`text-[10px] px-2 py-0.5 rounded-md font-bold uppercase border ${getCategoryColor(node.type)}`}>
                        {getNodeTitle(node)}
                      </span>
                      <span className="text-xs text-text-muted font-mono">{nid}</span>
                    </div>

                    <div className="p-6">
                      {outputs.length > 0 ? (
                        <div className="space-y-4">
                          {outputs.map((out, idx) => {
                            if (out.type === 'table') {
                              return <TableRenderer key={idx} data={out.data} />;
                            }
                            if (out.type === 'image') {
                              return (
                                <div key={idx} className="flex justify-center border border-border p-2 bg-black rounded-lg">
                                  <img
                                    src={`data:image/png;base64,${out.data}`}
                                    alt="Visual Node Output"
                                    className="max-h-80 object-contain rounded"
                                  />
                                </div>
                              );
                            }
                            return null;
                          })}
                        </div>
                      ) : (
                        <div className="flex flex-col items-center justify-center p-8 text-center text-text-muted">
                          <span className="text-2xl mb-1">📂</span>
                          <span className="text-xs font-semibold text-text-secondary">No rich outputs generated</span>
                          <span className="text-[10px] mt-0.5">This node did not output structured tables, metrics, or images in this run.</span>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------
// Structured Table Renderer Helper
// ---------------------------------------------------------------------
function TableRenderer({ data }: { data: { headers: string[]; rows: string[][] } }) {
  if (!data || !data.headers) return null;

  return (
    <div className="overflow-x-auto border border-border rounded-xl bg-bg-panel/50">
      <table className="min-w-full text-left border-collapse">
        <thead>
          <tr className="bg-bg-card border-b border-border">
            {data.headers.map((h, i) => (
              <th key={i} className="px-4 py-2.5 text-xs font-bold text-text-primary uppercase tracking-wider">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="divide-y divide-border">
          {data.rows.map((row, rIdx) => (
            <tr key={rIdx} className="hover:bg-bg-hover/40 transition">
              {row.map((val, cIdx) => (
                <td key={cIdx} className="px-4 py-2.5 text-xs text-text-secondary font-mono">
                  {val}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
